"""Photoreal coin flip renderer for Blender (Cycles/OptiX).

Produces the SAME output contract as gen_placeholder_frames.py so it drops
straight into the app: assets/coin/frame_000.png .. frame_089.png,
one seamless full rotation about the horizontal axis, frame 0 = HEADS up,
frame 45 = TAILS up, RGBA with transparent background.

The engraved faces come from height maps generated by gen_coin_maps.py
(tools/coin_maps/heads_height.png / tails_height.png): bump for the relief,
recesses matte + darkened (grime), plus micro-scratches and a reeded edge.

Usage:
    blender --background --python tools/render_coin.py
    # optional: --  --frames 90 --res 640 --samples 128
"""
import math
import os
import sys

import bpy  # type: ignore  (only available inside Blender)

# ---- args ----------------------------------------------------------------
argv = sys.argv[sys.argv.index("--") + 1:] if "--" in sys.argv else []


def arg(flag, default):
    return type(default)(argv[argv.index(flag) + 1]) if flag in argv else default


FRAMES = arg("--frames", 90)
RES = arg("--res", 640)
SAMPLES = arg("--samples", 128)
HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "assets", "coin")
MAPS = os.path.join(HERE, "coin_maps")
COIN_RADIUS = 1.0
COIN_THICK = 0.14

BRASS = (0.72, 0.55, 0.24, 1.0)       # aged brass base color
GRIME = (0.25, 0.17, 0.07, 1.0)       # recess patina


def reset_scene():
    # read_factory_settings(use_empty=True) breaks OPTIX enumeration in
    # headless sessions (silent CPU fallback) — clear the scene by hand.
    for obj in list(bpy.data.objects):
        bpy.data.objects.remove(obj, do_unlink=True)


def enable_gpu():
    prefs = bpy.context.preferences.addons["cycles"].preferences
    try:
        prefs.compute_device_type = "OPTIX"
    except Exception:
        prefs.compute_device_type = "CUDA"
    prefs.get_devices()
    for d in prefs.devices:
        d.use = d.type in {"OPTIX", "CUDA"}


def face_material(name, height_png, mirror_x):
    """Struck-metal face: bump from the height map, matte grime in recesses,
    micro-scratches in the roughness."""
    mat = bpy.data.materials.new(name)
    mat.use_nodes = True
    nt = mat.node_tree
    bsdf = nt.nodes["Principled BSDF"]
    out = nt.nodes["Material Output"]

    tex_coord = nt.nodes.new("ShaderNodeTexCoord")
    mapping = nt.nodes.new("ShaderNodeMapping")
    nt.links.new(tex_coord.outputs["Generated"], mapping.inputs["Vector"])
    if mirror_x:
        # Back face seen from -Z after a half-turn about X: unmirror AND
        # rotate 180° so the artwork reads upright when it lands → flip Y.
        mapping.inputs["Scale"].default_value = (1.0, -1.0, 1.0)
        mapping.inputs["Location"].default_value = (0.0, 1.0, 0.0)

    img = nt.nodes.new("ShaderNodeTexImage")
    img.image = bpy.data.images.load(height_png)
    img.image.colorspace_settings.name = "Non-Color"
    img.interpolation = "Cubic"
    nt.links.new(mapping.outputs["Vector"], img.inputs["Vector"])

    bump = nt.nodes.new("ShaderNodeBump")
    bump.inputs["Strength"].default_value = 0.5
    bump.inputs["Distance"].default_value = 0.03
    nt.links.new(img.outputs["Color"], bump.inputs["Height"])
    nt.links.new(bump.outputs["Normal"], bsdf.inputs["Normal"])

    # Recesses (height < field) turn matte and grimy.
    ramp = nt.nodes.new("ShaderNodeValToRGB")
    ramp.color_ramp.elements[0].position = 0.30
    ramp.color_ramp.elements[1].position = 0.55
    nt.links.new(img.outputs["Color"], ramp.inputs["Fac"])

    base_mix = nt.nodes.new("ShaderNodeMix")
    base_mix.data_type = "RGBA"
    base_mix.inputs["A"].default_value = GRIME
    base_mix.inputs["B"].default_value = BRASS
    nt.links.new(ramp.outputs["Color"], base_mix.inputs["Factor"])
    nt.links.new(base_mix.outputs["Result"], bsdf.inputs["Base Color"])

    # Roughness: polished high points, matte recesses, plus scratches.
    scratches = nt.nodes.new("ShaderNodeTexNoise")
    scratches.inputs["Scale"].default_value = 90.0
    scratches.inputs["Detail"].default_value = 6.0
    smap = nt.nodes.new("ShaderNodeMapping")
    smap.inputs["Scale"].default_value = (1.0, 18.0, 1.0)  # streaked
    nt.links.new(tex_coord.outputs["Generated"], smap.inputs["Vector"])
    nt.links.new(smap.outputs["Vector"], scratches.inputs["Vector"])

    rough_a = nt.nodes.new("ShaderNodeMath")  # base rough by relief
    rough_a.operation = "MULTIPLY_ADD"
    nt.links.new(ramp.outputs["Color"], rough_a.inputs[0])
    rough_a.inputs[1].default_value = -0.35   # high points → 0.22
    rough_a.inputs[2].default_value = 0.57    # recesses → 0.57

    rough_b = nt.nodes.new("ShaderNodeMath")  # scratches modulate ±0.08
    rough_b.operation = "MULTIPLY_ADD"
    nt.links.new(scratches.outputs["Fac"], rough_b.inputs[0])
    rough_b.inputs[1].default_value = 0.16
    rough_b.inputs[2].default_value = -0.08

    rough = nt.nodes.new("ShaderNodeMath")
    rough.operation = "ADD"
    rough.use_clamp = True
    nt.links.new(rough_a.outputs["Value"], rough.inputs[0])
    nt.links.new(rough_b.outputs["Value"], rough.inputs[1])
    nt.links.new(rough.outputs["Value"], bsdf.inputs["Roughness"])

    bsdf.inputs["Metallic"].default_value = 1.0
    if "Anisotropic" in bsdf.inputs:
        bsdf.inputs["Anisotropic"].default_value = 0.3
    nt.links.new(bsdf.outputs["BSDF"], out.inputs["Surface"])
    return mat


def edge_material():
    """Reeded (milled) rim: fine radial ridges via a sine bump."""
    mat = bpy.data.materials.new("Edge")
    mat.use_nodes = True
    nt = mat.node_tree
    bsdf = nt.nodes["Principled BSDF"]
    bsdf.inputs["Base Color"].default_value = BRASS
    bsdf.inputs["Metallic"].default_value = 1.0
    bsdf.inputs["Roughness"].default_value = 0.32

    tex_coord = nt.nodes.new("ShaderNodeTexCoord")
    sep = nt.nodes.new("ShaderNodeSeparateXYZ")
    nt.links.new(tex_coord.outputs["Object"], sep.inputs["Vector"])
    ang = nt.nodes.new("ShaderNodeMath")
    ang.operation = "ARCTAN2"
    nt.links.new(sep.outputs["Y"], ang.inputs[0])
    nt.links.new(sep.outputs["X"], ang.inputs[1])
    freq = nt.nodes.new("ShaderNodeMath")
    freq.operation = "MULTIPLY"
    nt.links.new(ang.outputs["Value"], freq.inputs[0])
    freq.inputs[1].default_value = 70.0
    ridges = nt.nodes.new("ShaderNodeMath")
    ridges.operation = "SINE"
    nt.links.new(freq.outputs["Value"], ridges.inputs[0])
    bump = nt.nodes.new("ShaderNodeBump")
    bump.inputs["Strength"].default_value = 0.6
    bump.inputs["Distance"].default_value = 0.015
    nt.links.new(ridges.outputs["Value"], bump.inputs["Height"])
    nt.links.new(bump.outputs["Normal"], bsdf.inputs["Normal"])
    return mat


def build_coin():
    bpy.ops.mesh.primitive_cylinder_add(
        vertices=192, radius=COIN_RADIUS, depth=COIN_THICK)
    coin = bpy.context.active_object
    bpy.ops.object.shade_smooth()
    mod = coin.modifiers.new("Bevel", "BEVEL")
    mod.width = 0.02
    mod.segments = 4

    heads = face_material("Heads", os.path.join(MAPS, "heads_height.png"),
                          mirror_x=False)
    tails = face_material("Tails", os.path.join(MAPS, "tails_height.png"),
                          mirror_x=True)
    edge = edge_material()
    coin.data.materials.append(heads)   # slot 0
    coin.data.materials.append(tails)   # slot 1
    coin.data.materials.append(edge)    # slot 2
    for poly in coin.data.polygons:
        if poly.normal.z > 0.5:
            poly.material_index = 0
        elif poly.normal.z < -0.5:
            poly.material_index = 1
        else:
            poly.material_index = 2

    coin.rotation_euler[0] = math.radians(90)  # heads face → camera
    return coin


def setup_lighting():
    # Warm tungsten key + brass rim + cool window fill; a dim warm world so
    # the metal always has something to reflect.
    def add_light(name, loc, energy, color, size):
        light = bpy.data.lights.new(name, "AREA")
        light.energy = energy
        light.color = color
        light.size = size
        obj = bpy.data.objects.new(name, light)
        obj.location = loc
        bpy.context.collection.objects.link(obj)
        # aim at the origin
        direction = -1
        obj.rotation_euler = (
            math.atan2(math.hypot(loc[0], loc[1]), loc[2] * -direction), 0,
            math.atan2(loc[1], loc[0]) + math.pi / 2)
        return obj

    add_light("Key", (-2.5, -2.5, 3.5), 900, (1.0, 0.82, 0.55), 3.5)
    add_light("Rim", (3.0, 2.5, 1.5), 450, (1.0, 0.68, 0.38), 2.5)
    add_light("Fill", (2.5, -3.0, -0.5), 140, (0.75, 0.82, 1.0), 5.0)

    world = bpy.data.worlds.new("World")
    world.use_nodes = True
    bg = world.node_tree.nodes["Background"]
    bg.inputs["Color"].default_value = (0.09, 0.07, 0.05, 1.0)
    bg.inputs["Strength"].default_value = 0.4
    bpy.context.scene.world = world


def setup_camera():
    cam_data = bpy.data.cameras.new("Cam")
    cam = bpy.data.objects.new("Cam", cam_data)
    cam.location = (0, -5.4, 0)
    cam.rotation_euler = (math.radians(90), 0, 0)
    cam_data.lens = 85
    bpy.context.collection.objects.link(cam)
    bpy.context.scene.camera = cam


def setup_render():
    scene = bpy.context.scene
    scene.render.engine = "CYCLES"
    scene.cycles.samples = SAMPLES
    scene.cycles.use_denoising = True
    scene.cycles.device = "GPU"
    scene.render.resolution_x = RES
    scene.render.resolution_y = RES
    scene.render.film_transparent = True
    scene.render.image_settings.file_format = "PNG"
    scene.render.image_settings.color_mode = "RGBA"
    scene.view_settings.view_transform = "Filmic"
    scene.view_settings.look = "Medium High Contrast"


def render_sequence(coin):
    os.makedirs(OUT, exist_ok=True)
    for i in range(FRAMES):
        path = os.path.join(OUT, f"frame_{i:03d}.png")
        theta = (i / FRAMES) * 2 * math.pi
        coin.rotation_euler[0] = math.radians(90) + theta  # spin about X
        bpy.context.scene.render.filepath = path
        bpy.ops.render.render(write_still=True)
    print(f"Rendered {FRAMES} frames -> {os.path.abspath(OUT)}")


def main():
    reset_scene()
    enable_gpu()
    coin = build_coin()
    setup_lighting()
    setup_camera()
    setup_render()
    render_sequence(coin)


if __name__ == "__main__":
    main()
